name: Increment patch version

on:
  push:
    branches:
      - main
    paths:
      - 'rastertoolkit/**'
      - 'pyproject.toml'

  # Allows manual run from the Actions tab
  workflow_dispatch:

permissions:
  contents: write # Allow writing to the repository (e.g., commits, pushes)

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version
        uses: callowayproject/bump-my-version@1.2.6
        with:
          args: patch -vv
