name: Increment patch version

on:
  push:
    branches:
      - main
    paths:
      - 'rastertoolkit/**'
      - 'pyproject.toml'

  # Allows manual run from the Actions tab
  workflow_dispatch:

permissions:
  contents: write # Allow writing to the repository (e.g., commits, pushes)

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install .[packaging]
      - name: Bump version
        run: |
          bump2version --commit patch pyproject.toml
          git config --global user.name "IDM Tools"
          git config --global user.email "idmtools@idmod.org"
          git push
