name: Increment patch version

on:
  push:
    branches:
      - main
    paths:
      - 'rastertoolkit/**'
      - '!rastertoolkit/version.py'
      - 'pyproject.toml'

  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.KFREY_PAT }}
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Run bump script
        run: |
          python3 ./.github/scripts/bump_version.py
      - name: Commit version change
        run: |
          git config user.name "Kurt Frey"
          git config user.email "kfrey@idmod.org"
          git add .
          git commit -m "Bump version"
          git push
